### ISSUE TITLE
How to java/io/File Object?

### ISSUE THREAD

**Issue by GeekTan** [jni-rs/jni-rs#343]
```
 let attach_guard = VM.attach_current_thread().unwrap();
        let jobj = attach_guard
            .new_object(
                "java/io/File",
                "(Ljava/lang/String;)V",
                &[{
                    let args = CString::new(String::from(path_name)).unwrap();
                    JValue::Object(JObject::from(args.as_ptr() as jobject))
                }],
            )
            .unwrap();
```
```
Exception in thread "Thread-1" java.lang.NullPointerException
        at java.base/java.io.UnixFileSystem.normalize(UnixFileSystem.java:86)
        at java.base/java.io.File.<init>(File.java:280)
```
How to create java/io/File Object?

**Comment by rib** [comment]
Here's an example of how you could construct a `java.io.File`, similar to above:

```rust
use jni::{JValue, jni_sig, jni_str, objects::JString};
fn main() -> jni::errors::Result<()> {
    let jvm = utils::jvm();
    jvm.attach_current_thread(|env| -> jni::errors::Result<()> {
        let path = JString::new(env, "./1.txt")?;
        let _jobj = env
            .new_object(
                jni_str!("java/io/File"),
                jni_sig!("(Ljava/lang/String;)V"),
                &[{ JValue::Object(&path) }],
            )
            .unwrap();
        Ok(())
    })
}
```

The main detail being that you needed to construct a `JString` reference for the file path (i.e. a `java.lang.String` reference)

With the latest jni 0.22 release, and the addition of the `bind_java_type!` macro, you could also create a mini `java.io.File` binding like this:

```rust
use jni::objects::JString;

jni::bind_java_type! {
    IoFile => java.io.File,
    constructors {
        fn new(path: JString),
    }
}

fn main() -> jni::errors::Result<()> {
    let jvm = utils::jvm();
    jvm.attach_current_thread(|env| -> jni::errors::Result<()> {
        let path = JString::new(env, "./1.txt")?;
        let _file = IoFile::new(env, path)?;
        Ok(())
    })
}
```

only about 4 years late, but hopefully this answers the question.
