### ISSUE TITLE
The drop of InternalAttachGuard object panics leading to JVM crash

### ISSUE THREAD

**Issue by kgrech** [jni-rs/jni-rs#354]
I am using jni-rs in the project where I also use the well-known rust [tracing](https://docs.rs/tracing/latest/tracing/) library. I am using jni = "0.18.0" and I am running on MacOS.

Here is the minimal reproducible example of the problem I am facing.

Java part:

Class:
```java
package com.example;

public class Daemon {
    static {
        System.loadLibrary("daemonjni");
    }
    public static native void start();
}
```

Test:
```java
package com.example;

import com.example.Daemon;
import org.junit.jupiter.api.Test;

public class DaemonThreadTest {

  @Test
  public void testSuccess() throws Exception {
    Daemon.start();
    Thread.sleep(5000);
  }
}
```

```rust
use tracing::Dispatch;
use tracing_subscriber::filter::LevelFilter;
use tracing_subscriber::util::SubscriberInitExt;
use tracing_subscriber::FmtSubscriber;

#[no_mangle]
pub unsafe extern "system" fn Java_com_example_Daemon_start(env: JNIEnv, j_class: JClass) {
    // Initialize the logging library (tracing)
    let subscriber = FmtSubscriber::builder()
        .with_max_level(LevelFilter::DEBUG)
        .finish();
    let dispatch: Dispatch = subscriber.into();
    dispatch.init();

    // Spawn a daemon thread
    let jvm = env.get_java_vm().expect("Unable get a JVM reference");
    std::thread::spawn(move || {
        jvm.attach_current_thread_as_daemon().expect("can't attach");
        println!("Daemon thread does nothing");
        // jvm.detach_current_thread(); // This solves the problem
    });
}
```

Note that the test has 5 seconds delay to ensure that the thread spawned by ``std::thread::spawn`` exits before the JVM exits.
The above code panics with the following stack trace:
```
thread '<unnamed>' panicked at 'use of std::thread::current() is not possible after the thread's local data has been destroyed', library/std/src/thread/mod.rs:677:35
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/option.rs:1854:5
   5: core::option::Option<T>::expect
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/option.rs:718:21
   6: std::thread::current
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/thread/mod.rs:677:5
   7: jni::wrapper::java_vm::vm::InternalAttachGuard::detach
             at /Users/kgrech/.cargo/registry/src/github.com-1ecc6299db9ec823/jni-0.18.0/src/wrapper/java_vm/vm.rs:424:13
   8: <jni::wrapper::java_vm::vm::InternalAttachGuard as core::ops::drop::Drop>::drop
             at /Users/kgrech/.cargo/registry/src/github.com-1ecc6299db9ec823/jni-0.18.0/src/wrapper/java_vm/vm.rs:435:25
   9: core::ptr::drop_in_place<jni::wrapper::java_vm::vm::InternalAttachGuard>
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ptr/mod.rs:486:1
  10: core::ptr::drop_in_place<core::option::Option<jni::wrapper::java_vm::vm::InternalAttachGuard>>
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ptr/mod.rs:486:1
  11: core::ptr::drop_in_place<core::cell::UnsafeCell<core::option::Option<jni::wrapper::java_vm::vm::InternalAttachGuard>>>
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ptr/mod.rs:486:1
  12: core::ptr::drop_in_place<core::cell::RefCell<core::option::Option<jni::wrapper::java_vm::vm::InternalAttachGuard>>>
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ptr/mod.rs:486:1
  13: core::ptr::drop_in_place<core::option::Option<core::cell::RefCell<core::option::Option<jni::wrapper::java_vm::vm::InternalAttachGuard>>>>
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ptr/mod.rs:486:1
  14: core::mem::drop
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/mem/mod.rs:974:24
  15: std::thread::local::fast::destroy_value
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/thread/local.rs:1033:13
  16: std::sys::unix::thread_local_dtor::register_dtor::run_dtors
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys/unix/thread_local_dtor.rs:89:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
```

Note that either disabling tracing library or uncommenting ``// jvm.detach_current_thread();`` line solves the problem. 

The root cause of the problem seems to be the call to [std::thread::current](https://doc.rust-lang.org/std/thread/fn.current.html) function done in the ``debug!`` macro called by [InternalAttachGuard:: detach](https://github.com/jni-rs/jni-rs/blob/cced1925fa13c5b2eece5d3de81ec3b1abcef7e0/src/wrapper/java_vm/vm.rs#L422). This method is called during the drop method. 

However, the ``std::thread::current`` can [panic](https://doc.rust-lang.org/src/std/thread/mod.rs.html#680-685) in certain cases. Unfortunately, I was not able to figure out a lot of information across rust documentation on what exactly causes the thread local data to be destroyed before local variables captured by the thread a dropped. This discussion looks somewhat relevant discussion [here](https://internals.rust-lang.org/t/thread-lifetime-for-tls/13550/3). It is still unclear why tracing library causes the above side effect. Note that the behaviour would likely be not consistent across the platforms as the call originates from `` std::sys::unix::thread_local_dtor::register_dtor::run_dtors`` part of rust std-lib.

I think the tracing library here is nothing more than one possible way to reproduce the problem. The overall conclusion I have is that calling ``std::thread::current`` in the stack trace of the drop method is not the best idea.  Since the call to  ``std::thread::current`` is done only for debug purposes only, would it make sense to remove the calls to it for the sake of stability rather then relying on not so well documented and platform specific behaviour of the code?

**Comment by rib** [comment]
Closing since #355 was merged, thanks.
