### ISSUE TITLE
Doesn't support java.class.path=some.jar?

### ISSUE THREAD

**Issue by robberphex** [jni-rs/jni-rs#389]
I tried to use option `-Djava.class.path` to load class from jar:

```rust
fn main() {
    let jvm_args = InitArgsBuilder::new()
        .version(JNIVersion::V8)
        .option("-Djava.class.path=/path/to/arthas-boot.jar")
        .build()
        .unwrap();
    let jvm = JavaVM::new(jvm_args).unwrap();
    
    let env = jvm.attach_current_thread().unwrap();

    env.find_class("com.taobao.arthas.boot.Bootstrap").unwrap();
}
```
`arthas-boot.jar` is from [arthas](https://github.com/alibaba/arthas/releases).

But failed: 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JavaException', src/bin/arthas.rs:13:56
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1814:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1107:23
   4: arthas::main
             at ./src/bin/arthas.rs:13:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: com.taobao.arthas.boot.Bootstrap
```

It doesn't load class from jar file, is there something wrong in my code?

**Comment by rib** [comment]
Can you maybe try adding `.option("-Xcheck:jni")` and `.option("-verbose:jni")` as options to hopefully confirm that the options are being interpreted when loading the `JavaVM`

E.g. If I make a change like this in `jni-rs`:

```diff
diff --git a/tests/util/mod.rs b/tests/util/mod.rs
index fb07386..207a814 100644
--- a/tests/util/mod.rs
+++ b/tests/util/mod.rs
@@ -16,6 +16,7 @@ pub fn jvm() -> &'static Arc<JavaVM> {
         let jvm_args = InitArgsBuilder::new()
             .version(JNIVersion::V8)
             .option("-Xcheck:jni")
+            .option("-verbose:jni")
             .build()
             .unwrap_or_else(|e| panic!("{:#?}", e));

```

and then run `cargo test --features=invocation -- --nocapture` I see lots of verbose info like:
```
[0.005s][debug][jni,resolve] Checked JNI functions are being used to validate JNI usage
[0.012s][debug][jni,resolve] [Registering JNI native method java.lang.Object.hashCode]
[0.013s][debug][jni,resolve] [Registering JNI native method java.lang.Object.wait0]
[0.013s][debug][jni,resolve] [Registering JNI native method java.lang.Object.notify]
[0.013s][debug][jni,resolve] [Registering JNI native method java.lang.Object.notifyAll]
[0.013s][debug][jni,resolve] [Registering JNI native method java.lang.Object.clone]
[0.017s][debug][jni,resolve] [Dynamic-linking native method java.lang.System.registerNatives ... JNI]
[0.017s][debug][jni,resolve] [Registering JNI native method java.lang.System.currentTimeMillis]
[0.017s][debug][jni,resolve] [Registering JNI native method java.lang.System.nanoTime]
[0.017s][debug][jni,resolve] [Registering JNI native method java.lang.System.arraycopy]
...
```

which suggests that the options are being passed through properly to the JVM implementation.

If it looks like the options are being passed through then I would guess then that maybe there is something about the class path or the `.jar` that's not correct perhaps?

**Comment by rib** [comment]
Oh, actually I think it's probably just that you need to use slashes instead of dots here:
> env.find_class("com.taobao.arthas.boot.Bootstrap").unwrap();

like:
```rust
env.find_class("com/taobao/arthas/boot/Bootstrap").unwrap();
```

Hope that helps

**Comment by rib** [comment]
Trying this out, with the arthas binaries linked above worked:

```rust
use jni::{InitArgsBuilder, JNIVersion, JavaVM};

fn main() {
    let jvm_args = InitArgsBuilder::new()
        .version(JNIVersion::V8)
        .option("-Djava.class.path=./arthas-bin/arthas-boot.jar")
        .build()
        .unwrap();
    let jvm = JavaVM::new(jvm_args).unwrap();

    let env = jvm.attach_current_thread().unwrap();

    env.find_class("com/taobao/arthas/boot/Bootstrap").unwrap();
}
```

so yeah it's just that `find_class()` followed the JNI convention of using slashes instead of dots to separate namespaces.
