### ISSUE TITLE
Does it support Apple M1?

### ISSUE THREAD

**Issue by PeakerChen** [jni-rs/jni-rs#553]

**Comment by PeakerChen** [comment]
Exception in thread "main" java.lang.UnsatisfiedLinkError: /Users/chenzhanfeng/Documents/Rust-App/jni-demo/mylib/target/debug/libmylib.dylib: dlopen(/Users/chenzhanfeng/Documents/Rust-App/jni-demo/mylib/target/debug/libmylib.dylib, 0x0001): tried: '/Users/chenzhanfeng/Documents/Rust-App/jni-demo/mylib/target/debug/libmylib.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/chenzhanfeng/Documents/Rust-App/jni-demo/mylib/target/debug/libmylib.dylib' (no such file), '/Users/chenzhanfeng/Documents/Rust-App/jni-demo/mylib/target/debug/libmylib.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1850)
        at java.lang.Runtime.loadLibrary0(Runtime.java:871)
        at java.lang.System.loadLibrary(System.java:1122)
        at HelloWorld.<clinit>(HelloWorld.java:13)

**Comment by argv-minus-one** [comment]
According to the error message, `mylib` is compiled for arm64 (Apple Silicon), but the program trying to load it is compiled for x86_64 (Intel).

My first guess is that you're using a JDK/JRE that was compiled for x86_64 and is running in Rosetta. Please make sure you're using a JDK/JRE compiled for arm64.

You might also compile `mylib` for both arm64 and x86_64, and then put them together into a universal library using the `lipo` program. Then it'll work either way.
